version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Pass12345
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    restart: unless-stopped

  app:
    build: .
    container_name: invest-calc-app
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Pass12345
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: